# Generated by Django 5.1.7 on 2025-03-16 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of sales entry')),
                ('product_category', models.CharField(help_text='Product category (e.g. Electronics, Clothing)', max_length=100)),
                ('sales', models.FloatField(help_text='Sales amount in USD', validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name_plural': 'Historical Sales Data',
                'ordering': ['-date'],
            },
        ),
    ]
